/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication7;

import java.awt.List;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hamza
 */
public class ErrorHandle extends javax.swing.JFrame {

    //modify to read an element from rpi files.

    public static String FilePath = "/home/pi/tensorflow1/models/research/object_detection/factures/facture_affichage.txt";
    public File file =  new File(FilePath);
    public int Avocats, Bananes, Pomme, elem4, elem5 = 0;
    public int AvocatsIndex, BananesIndex, PommeIndex, elem4Index, elem5Index = 0;
    public double AvocatsPrice = 1.49;
    public double BananesPrice = 1.99;
    public double PommePrice = 2.06;
    public double elem4Price = 2;
    public double elem5Price = 2;
    public double AvocatsPriceTTC , BananesPriceTTC, PommePriceTTC, elem4PriceTTC, elem5PriceTTC = 0;
    public String AvocatsType, BananesType, PommeType, elem4Type, elem5Type;
    /**
     * Creates new form NewJFrame1
     */
    
    public ErrorHandle() {
        initComponents();
        //récupérer les élements de la liste python et affichage
        
        int i = 0;
        try {
                
                BufferedReader br = new BufferedReader(new FileReader(FilePath));
                String firstLine = br.readLine().trim();
                String[] columnsName = firstLine.split("\\t");
                DefaultTableModel model;
                model = (DefaultTableModel)jTable1.getModel();
                model.setColumnIdentifiers(columnsName);
                
                Object[] tableLines = br.lines().toArray();
                
                for (Object tableLine : tableLines) {
                    String line = tableLine.toString().trim();
                    String[] dataRow = line.split("\\t");
                    model.addRow(dataRow);
                    i = i+1;
                }
            } catch (IOException ex) {
                Logger.getLogger(ErrorHandle.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        System.out.println("Nb lignes dans le tableau : "+i);
        
        for (int j=0 ; j < i ; j++){
            System.out.println("STEP : "+j);
            System.out.println("DETECTED : "+jTable1.getModel().getValueAt(j,2));
            if(jTable1.getModel().getValueAt(j,2).equals("Avocat")){
                Avocats = Integer.parseInt((String) jTable1.getModel().getValueAt(j,0));
                AvocatsIndex = j;
                System.out.println("GET AVOCAT");
                AvocatsType = String.valueOf(jTable1.getModel().getValueAt(j,1));
                System.out.println("Type de vente : " + AvocatsType);
            }
            if(jTable1.getModel().getValueAt(j,2).equals("banane")){
                Bananes = Integer.parseInt((String)jTable1.getModel().getValueAt(j,0));
                BananesIndex = j;
                System.out.println("GET BANANE");
                BananesType = String.valueOf(jTable1.getModel().getValueAt(j,1));
                System.out.println("Type de vente : " + BananesType);
            }
            if(jTable1.getModel().getValueAt(j,2).equals("pomme")){
                Pomme = Integer.parseInt((String)jTable1.getModel().getValueAt(j,0));
                PommeIndex = j;
                System.out.println("GET POMME");
                PommeType = String.valueOf(jTable1.getModel().getValueAt(j,1));
                System.out.println("Type de vente : " + PommeType);
            } 
        }
        
        jLabel1.setText(String.valueOf(Avocats));
        jLabel4.setText(String.valueOf(Bananes));
        jLabel6.setText(String.valueOf(Pomme));
        AvocatsPriceTTC = Avocats*AvocatsPrice;
        BananesPriceTTC = Bananes*BananesPrice;
        PommePriceTTC   = Pomme*PommePrice;
        
        System.out.println("Nb avocats : " +Avocats);
        System.out.println("Nb Bananes : " +Bananes);
        System.out.println("Nb Pomme: "    +Pomme);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(120, 383, 30, 30);

        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(40, 383, 30, 30);

        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(640, 290, 150, 170);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 380, 40, 40);

        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(190, 380, 30, 30);

        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(270, 383, 30, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(240, 380, 40, 40);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(520, 360, 70, 40);

        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(510, 420, 80, 23);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(440, 100, 350, 130);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication7/saisie erreur.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   // VALIDER CHANGEMENTS DE LA LISTE MANUELLE
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // add button :
        Avocats = Avocats+1;
        AvocatsPriceTTC = AvocatsPrice*Avocats;
        jLabel1.setText(String.valueOf(Avocats));
        System.out.println("Avocats : "+Avocats);
        System.out.println("Prix Avocats : "+AvocatsPriceTTC);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // del :
        Avocats = Avocats - 1;
        if (Avocats < 0){
            Avocats = 0;
        }
        AvocatsPriceTTC = AvocatsPrice*Avocats;
        jLabel1.setText(String.valueOf(Avocats));
        System.out.println("Avocats : "+Avocats);
        System.out.println("Prix Avocats : "+AvocatsPriceTTC);
     
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    String newFileFacture = "/home/pi/tensorflow1/models/research/object_detection/factures/facture_affichage.txt";
    // create a write
    File f = new File(FilePath);
        if(f.exists() && !f.isDirectory()) { //GESTION D'ERREUR SI KG ET PIECE
            f.delete();
        // do something
        }
    // create a csv writer
    try (PrintWriter writer = new PrintWriter(new File(newFileFacture))){
        StringBuilder header = new StringBuilder();
        header.append("Qte");
        header.append("\t");
        header.append("Type");
        header.append("\t");
        header.append("Design");
        header.append("\t");
        header.append("Prix/u");
        header.append("\t");
        header.append("Prix HT");
        header.append("\n");
        if (Avocats != 0){
            header.append(String.valueOf(Avocats));
            header.append("\t");
            header.append(AvocatsType);
            header.append("\t");
            header.append("avocat");
            header.append("\t");
            header.append(String.valueOf(AvocatsPrice));
            header.append("\t");
            header.append(String.valueOf(AvocatsPriceTTC));
            header.append("\n");
        }
        if (Bananes != 0){
            header.append(String.valueOf(Bananes));
            header.append("\t");
            header.append(BananesType);
            header.append("\t");
            header.append("banane");
            header.append("\t");
            header.append(String.valueOf(BananesPrice));
            header.append("\t");
            header.append(String.valueOf(BananesPriceTTC));
            header.append("\n");
        }
        if (Pomme != 0){
            header.append(String.valueOf(Pomme));
            header.append("\t");
            header.append(PommeType);
            header.append("\t");
            header.append("pomme");
            header.append("\t");
            header.append(String.valueOf(PommePrice));
            header.append("\t");
            header.append(String.valueOf(PommePriceTTC));
            header.append("\n");
        }
        writer.write(header.toString());
        System.out.println("WRITE CORRECTION DONE");

        
    }   catch (FileNotFoundException ex) {
            Logger.getLogger(ErrorHandle.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Bananes = Bananes+1;
        BananesPriceTTC = BananesPrice*Avocats;
        jLabel4.setText(String.valueOf(Bananes));
        System.out.println("Bananes : "+Bananes);
        System.out.println("Prix Bananes: "+BananesPriceTTC);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        Bananes = Bananes - 1;
        if (Bananes < 0){
            Bananes = 0;
        }
        BananesPriceTTC = BananesPrice*Bananes;
        jLabel4.setText(String.valueOf(Bananes));
        System.out.println("Bananes : "+Bananes);
        System.out.println("Prix Bananes : "+BananesPriceTTC);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        
        //  /home/pi/tensorflow1/models/research/object_detection/hx711/temp/pesee_java.txt is the real path.
        
        File f = new File("/home/pi/tensorflow1/models/research/object_detection/hx711/temp/pesee_java.txt");

        while (!(f.isFile())) { 
            System.out.println("entree dans la boucle de verif du fichier 2");
            try {
                // do something
                TimeUnit.SECONDS.sleep(4);
                System.out.println("delai de 1 s");
            } catch (InterruptedException ex) {
                Logger.getLogger(ErrorHandle.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        String df = null;
        BufferedReader br1 = null;
        StringBuilder sb = new StringBuilder();
        String line = null;
        try {
            
            while (df == null) {
                br1 = new BufferedReader(new FileReader(f));
                System.out.println("toujours pas eu de pesee");
                line = br1.readLine();
                df = line;
                TimeUnit.SECONDS.sleep(1);
                System.out.println(line);
                jLabel6.setText("Pesee en cours");
            }
        } catch (IOException ex) {
            Logger.getLogger(ErrorHandle.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
                Logger.getLogger(ErrorHandle.class.getName()).log(Level.SEVERE, null, ex);
            }
        jLabel6.setText(df+"g");
        Pomme = Integer.parseInt(df.trim());
        PommePriceTTC = (Pomme*0.001)*PommePrice;
        
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ErrorHandle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ErrorHandle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ErrorHandle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ErrorHandle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ErrorHandle().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
